apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playzuno-demo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: harbor.apps.estreetz.com/playzuno/playzuno-demo
    argocd-image-updater.argoproj.io/harbor.apps.estreetz.com/playzuno/playzuno-demo.update-strategy: latest
spec:
  project: default
  source:
    repoURL: "https://github.com/sukuna-uni/playzuno-demo.git"
    targetRevision: HEAD # Could also be a specific branch/tag
    path: "k8s/manifests" # The path within the repo where the manifests are located
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
